version: '3.7'

x-pg-common: &pg-common
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"

services:
    stage:
        <<: *pg-common
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${PG_USER}", "-d", "dbStage"]
            interval: 5s
            retries: 5
        ports:
            - '5433:5432'
        volumes: 
            - stage_data:/var/lib/postgresql/data
    prod:
        <<: *pg-common
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${PG_USER}", "-d", "dbProd"]
            interval: 5s
            retries: 5
        ports:
            - '5434:5432'
        volumes: 
            - prod_data:/var/lib/postgresql/data

volumes:
  stage_data:
  prod_data:


# https://stackoverflow.com/questions/55327571/postgresql-dockerfile-create-user-and-database-from-entrypoint-script